---
- name: Install Podman packages
  ansible.builtin.include_tasks: packages.yaml
  tags: [podman_base, packages]

- name: Configure Podman user settings
  ansible.builtin.include_tasks: user_setup.yaml
  tags: [podman_base, user_setup]

- name: Configure Podman subordinate IDs
  ansible.builtin.include_tasks: subids.yaml
  tags: [podman_base, subids]

- name: Verify Podman installation
  ansible.builtin.include_tasks: verification.yaml
  tags: [podman_base, verification]
