---
- name: Ensure lingering is enabled for user
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ podman_user }}
  become: true
  changed_when: false
  when: podman_lingering_enabled | default(true)

- name: Create Podman directories structure
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/{{ item }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: '0755'
  loop: "{{ podman_work_directories }}"

- name: Set secure permissions on .config directory
  ansible.builtin.file:
    path: "/home/{{ podman_user }}/.config"
    mode: '0700'
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
  become: true
  become_user: "{{ podman_user }}"
