---
- name: Install HAProxy package
  ansible.builtin.include_tasks: packages.yaml
  tags: [haproxy, packages]

- name: Prepare HAProxy SSL material
  ansible.builtin.include_tasks: ssl.yaml
  tags: [haproxy, ssl]

- name: Deploy HAProxy configuration
  ansible.builtin.include_tasks: configuration.yaml
  tags: [haproxy, configuration]

- name: Configure HAProxy security settings
  ansible.builtin.include_tasks: security.yaml
  tags: [haproxy, security]

- name: Ensure HAProxy service is running
  ansible.builtin.include_tasks: service.yaml
  tags: [haproxy, service]
