all:
  children:
    control_hosts:
      hosts:
        nat:
          ansible_host: localhost

    proxy_hosts:
      hosts:
        proxy:
          ansible_host: proxy-ansible

    container_hosts:
      hosts:
        pods:
          ansible_host: pods-ansible

    cache_hosts:
      hosts:
        redis:
          ansible_host: redis-ansible
    
    ipa_hosts:
      hosts:
        ipa:
          ansible_host: ipa-ansible

    monitoring_hosts:
      hosts:
        monitor:
          ansible_host: monitor-ansible
