---
- name: Common base configuration
  hosts: all
  gather_facts: true
  roles:
    - common
  tags: [common]

- name: Redis configuration
  hosts: cache_hosts
  gather_facts: false
  roles:
    - redis
  tags: [redis]

- name: HAProxy configuration
  hosts: proxy_hosts
  gather_facts: false
  roles:
    - haproxy
  tags: [haproxy, proxy]

- name: Podman base configuration
  hosts: container_hosts
  gather_facts: false
  roles:
    - podman_base
  tags: [podman, containers]

- name: GLPI container configuration
  hosts: container_hosts
  gather_facts: false
  roles:
    - glpi_pod
  tags: [glpi, containers]

- name: WikiJS container configuration
  hosts: container_hosts
  gather_facts: false
  roles:
    - wikijs_pod
  tags: [wikijs, containers]

- name: FreeIPA server configuration
  hosts: ipa_hosts
  gather_facts: false
  roles:
    - freeipa_server
  tags: [freeipa, identity]

- name: FreeIPA client configuration
  hosts:
      - control_hosts
      - proxy_hosts
      - container_hosts
      - cache_hosts
  gather_facts: false
  roles:
    - freeipa_client
  tags: [freeipa, identity]

- name: Prometheus configuration
  hosts: monitoring_hosts
  gather_facts: false
  roles:
    - prometheus
  tags: [prometheus, monitoring]

- name: Exporters configuration
  hosts: monitoring_hosts
  gather_facts: false
  roles:
    - exporters
  tags: [exporters, monitoring]

- name: Loki configuration
  hosts: monitoring_hosts
  gather_facts: false
  roles:
    - loki
  tags: [loki, monitoring]

- name: Fluent Bit configuration
  hosts: monitoring_hosts
  gather_facts: false
  roles:
    - fluentbit
  tags: [fluentbit, monitoring]

- name: Grafana configuration
  hosts: monitoring_hosts
  gather_facts: false
  roles:
    - grafana
  tags: [grafana, monitoring]
