---
- name: Ensure /etc/hosts entries are present
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }} {{ item.name }} {% for alias in item.aliases | default([]) %}{{ alias }} {% endfor %}"
    regexp: "^{{ item.ip }}\\s+{{ item.name }}(\\s|$)"
    state: present
  loop: "{{ hosts_entries }}"
  when: hosts_entries is defined
