---
# Network interfaces configuration
ipa_interfaces:
  external:
    interface: ens224
    ip: "172.24.133.219"
    netmask: "24"
    gateway: "{{ public_network_gateway }}"
    zone: external
  
  internal:
    interface: ens160
    ip: "192.168.216.10"
    netmask: "24"
    zone: internal

# Firewall zones
firewall_zones:
  external:
    interface: "{{ ipa_interfaces.external.interface }}"
    services: ["https"]
    masquerade: false

  internal:
    interface: "{{ ipa_interfaces.internal.interface }}"
    services:
      - ssh
    ports:
      - "389/tcp" # LDAP
      - "636/tcp" # LDAPS
      - "88/tcp" # Kerberos
      - "88/udp" # Kerberos
      - "464/tcp" # kpasswd
      - "464/udp" # kpasswd
      - "53/tcp" # DNS
      - "53/udp" # DNS
      - "123/udp" # NTP
      - "9100/tcp" # Node Exporter
    masquerade: false

exporters_node_exporter_listen_address: "{{ ipa_interfaces.internal.ip }}"
