---
# Network interfaces
proxy_interfaces:
  public:
    interface: ens256
    ip: "172.24.133.218"
    netmask: "24"
    gateway: "172.24.133.1"
    zone: public

  internal:
    interface: ens160
    ip: "192.168.216.4"
    netmask: "24"
    zone: internal

  application:
    interface: ens224
    ip: "192.168.218.1"
    netmask: "24"
    zone: application

  monitorproxy:
    interface: ens161
    ip: "192.168.217.1"
    netmask: "24"
    zone: monitorproxy

# Firewall zones
firewall_zones:
  public:
    interface: "{{ proxy_interfaces.public.interface }}"
    services: ["https"]
    ports: ["8443/tcp"]
    masquerade: false

  internal:
    interface: "{{ proxy_interfaces.internal.interface }}"
    services: ["ssh"]
    ports:
      - "9100/tcp" # Node Exporter
      - "9101/tcp" # HAProxy Exporter
    masquerade: false

  application:
    interface: "{{ proxy_interfaces.application.interface }}"
    services: []
    ports:
      - "{{ backend_servers.glpi.port }}/tcp" # GLPI
      - "{{ backend_servers.wikijs.port }}/tcp" # Wiki.js
    masquerade: false

  monitorproxy:
    interface: "{{ proxy_interfaces.monitorproxy.interface }}"
    services: []
    ports:
      - "3000/tcp" # Grafana
    forward: false
    masquerade: false

# Backend servers
backend_servers:
  glpi:
    address: "192.168.218.2"
    port: "8080"
  wikijs:
    address: "192.168.218.2"
    port: "3000"
  grafana:
    address: "192.168.217.2"
    port: "3000"


# SSL certificate generation parameters
haproxy_ssl:
  key_path: "/etc/ssl/private/glpi_proxy.key"
  crt_path: "/etc/ssl/certs/glpi_proxy.crt"
  cert_path: "/etc/ssl/private/glpi_proxy.pem"

  country: "CR"
  state: "SanJose"
  city: "SanJose"
  org: "Universidad de Costa Rica"
  ou: "Infrastructure"
  email: "infra@ucr.ac.cr"
  cn: "{{ proxy_interfaces.public.ip }}"
  san_ips:
    - "{{ proxy_interfaces.public.ip }}"
  san_dns:
    - "glpi.infra.local"
    - "wiki.infra.local"
    - "proxy.infra.local"
  days: 365
  key_size: 2048

# HAProxy
haproxy:
  ssl_cert_path: "{{ haproxy_ssl.cert_path }}"

  global:
    maxconn: 4000
    user: "haproxy"
    group: "haproxy"
    ca_base: "/etc/ssl/certs"
    crt_base: "/etc/ssl/private"

  defaults:
    mode: "http"
    timeout_connect: "5s"
    timeout_client: "50s"
    timeout_server: "50s"

  frontends:
    http:
      bind: "{{ proxy_interfaces.public.ip }}:80"
      redirect_https: true

    https-in:
      bind: "{{ proxy_interfaces.public.ip }}:443"
      domains:
        glpi: "glpi.infra.local"
        wikijs: "wiki.infra.local"
        grafana: "grafana.infra.local"
      default_backend: glpi
    
    wikijs-https-in:
      bind: "{{ proxy_interfaces.public.ip }}:8443"
      default_backend: wikijs

    grafana-https-in:
      bind: "{{ proxy_interfaces.public.ip }}:9443"
      default_backend: grafana

    stats_prometheus:
      ssl: false
      bind: "{{ proxy_interfaces.internal.ip }}:9101"
      mode: "http"
      options:
        - "dontlog-normal"
      http_request:
        - "use-service prometheus-exporter if { path /metrics }"

  backends:
    glpi:
      health_check_path: "/"
      health_check_status: 200
      servers:
        glpi-pods:
          address: "{{ backend_servers.glpi.address }}"
          port: "{{ backend_servers.glpi.port }}"
          check_interval: "10s"
          fall: 3
          rise: 2

    wikijs:
      health_check_path: "/"
      health_check_status: 200
      servers:
        wikijs-pods:
          address: "{{ backend_servers.wikijs.address }}"
          port: "{{ backend_servers.wikijs.port }}"
          check_interval: "10s"
          fall: 3
          rise: 2

    grafana:
      health_check_path: ""
      health_check_status: 200
      servers:
        grafana-monitor:
          address: "{{ backend_servers.grafana.address }}"
          port: "{{ backend_servers.grafana.port }}"
          check_interval: "10s"
          fall: 3
          rise: 2

fluent_bit_extra_tail_paths:
  - tag: haproxy.log
    path: /var/log/haproxy.log
