---
- name: Validate required variables
  ansible.builtin.include_tasks: assertions.yaml
  tags: [wikijs_pod, assertions]

- name: Manage Podman secrets
  ansible.builtin.include_tasks: podman_secrets.yaml
  tags: [wikijs_pod, podman_secrets]

- name: Deploy configuration files
  ansible.builtin.include_tasks: configuration_files.yaml
  tags: [wikijs_pod, configuration_files]

- name: Deploy quadlets
  ansible.builtin.include_tasks: quadlets.yaml
  tags: [wikijs_pod, quadlets]

- name: Set volume permissions
  ansible.builtin.include_tasks: volumes_permissions.yaml
  tags: [wikijs_pod, volumes_permissions]

- name: Start WikiJS pod
  ansible.builtin.include_tasks: start_pod.yaml
  tags: [wikijs_pod, start_pod]
