---
- name: Verify postgres_wikijs_password secret
  ansible.builtin.command:
    cmd: podman secret inspect postgres_wikijs_password
  register: secret_postgres_wikijs
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ podman_user }}"

- name: Create postgres_wikijs_password secret
  ansible.builtin.shell:
    cmd: printf '%s' "{{ vault_postgres_wikijs_password }}" | podman secret create postgres_wikijs_password -
  when: secret_postgres_wikijs.rc != 0
  become: true
  become_user: "{{ podman_user }}"
  no_log: true
