---
- name: Download prometheus binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
    checksum: "{{ prometheus_checksum }}"
    mode: "0644"

- name: Extract prometheus binary
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.tar.gz"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  when: not ansible_check_mode


- name: Install prometheus binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_bin_dir }}/{{ item }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  loop:
    - prometheus
    - promtool
  notify: restart prometheus
  when: not ansible_check_mode
