---
- name: Assert required variables for glpi_pod role
  ansible.builtin.import_tasks: assertions.yaml
  tags: [glpi_pod, assertions]

- name: Manage Podman secrets for GLPI
  ansible.builtin.import_tasks: podman_secrets.yaml
  tags: [glpi_pod, podman_secrets]

- name: Deploy configuration files for GLPI and MariaDB
  ansible.builtin.import_tasks: configuration_files.yaml
  tags: [glpi_pod, configuration_files]

- name: Deploy Quadlets for GLPI pod
  ansible.builtin.import_tasks: quadlets.yaml
  tags: [glpi_pod, quadlets]

- name: Set Volumes Permissions
  ansible.builtin.import_tasks: volumes_permissions.yaml
  tags: [glpi_pod, volumes_permissions]

- name: Start GLPI pod
  ansible.builtin.import_tasks: start_pod.yaml
  tags: [glpi_pod, start_pod]

- name: Deploy configuration files for Redis
  ansible.builtin.import_tasks: redis.yaml
  tags: [glpi_pod, redis]
