---
- name: Verify secret mariadb_root_password
  ansible.builtin.command:
    cmd: podman secret inspect mariadb_root_password
  register: secret_mariadb_root
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ podman_user }}"

- name: Create secret mariadb_root_password
  ansible.builtin.shell:
    cmd: printf '%s' "{{ vault_mariadb_root_password }}" | podman secret create mariadb_root_password -
  when: secret_mariadb_root.rc != 0
  become: true
  become_user: "{{ podman_user }}"
  no_log: true

- name: Verify secret mariadb_glpi_password
  ansible.builtin.command:
    cmd: podman secret inspect mariadb_glpi_password
  register: secret_mariadb_glpi
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ podman_user }}"

- name: Create secret mariadb_glpi_password
  ansible.builtin.shell:
    cmd: printf '%s' "{{ vault_mariadb_glpi_password }}" | podman secret create mariadb_glpi_password -
  when: secret_mariadb_glpi.rc != 0
  become: true
  become_user: "{{ podman_user }}"
  no_log: true

- name: Verify secret redis_password
  ansible.builtin.command:
    cmd: podman secret inspect redis_password
  register: secret_redis
  failed_when: false
  changed_when: false
  become: true
  become_user: "{{ podman_user }}"

- name: Create secret redis_password
  ansible.builtin.shell:
    cmd: printf '%s' "{{ vault_redis_password }}" | podman secret create redis_password -
  when: secret_redis.rc != 0
  become: true
  become_user: "{{ podman_user }}"
  no_log: true
