---
- name: Install Redis packages
  ansible.builtin.include_tasks: packages.yaml
  tags: [redis, packages]

- name: Deploy Redis configuration
  ansible.builtin.include_tasks: configuration.yaml
  tags: [redis, configuration]

- name: Validate Redis runtime
  ansible.builtin.include_tasks: runtime.yaml
  tags: [redis, runtime]

- name: Ensure Redis service is enabled
  ansible.builtin.include_tasks: service.yaml
  tags: [redis, service]

- name: Perform Redis post-checks
  ansible.builtin.include_tasks: verification.yaml
  tags: [redis, verification]
